DROP TABLE IF EXISTS payouts CASCADE;
DROP TABLE IF EXISTS live_sessions CASCADE;
DROP TABLE IF EXISTS seasons CASCADE;
DROP TABLE IF EXISTS ledger CASCADE;
DROP TABLE IF EXISTS votes CASCADE;
DROP TABLE IF EXISTS drops CASCADE;
DROP TABLE IF EXISTS dares CASCADE;
DROP TABLE IF EXISTS users CASCADE;
